# Generated by Django 5.2 on 2025-04-15 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Epilogapp', '0002_skincarerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='skincarerecord',
            name='concerns',
            field=models.TextField(blank=True, verbose_name='肌悩み'),
        ),
        migrations.AddField(
            model_name='skincarerecord',
            name='ingredients',
            field=models.TextField(blank=True, verbose_name='気になる成分'),
        ),
        migrations.AddField(
            model_name='skincarerecord',
            name='morning_items',
            field=models.TextField(blank=True, verbose_name='朝の使用アイテム'),
        ),
        migrations.AddField(
            model_name='skincarerecord',
            name='night_items',
            field=models.TextField(blank=True, verbose_name='夜の使用アイテム'),
        ),
    ]
