# Generated by Django 5.2 on 2025-04-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Epilogapp', '0003_skincarerecord_concerns_skincarerecord_ingredients_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='肌悩み')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='成分名')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='商品名')),
                ('brand', models.CharField(max_length=100, verbose_name='ブランド名')),
                ('category', models.CharField(max_length=100, verbose_name='カテゴリ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('concerns', models.ManyToManyField(blank=True, to='Epilogapp.concern', verbose_name='対応する肌悩み')),
                ('ingredients', models.ManyToManyField(blank=True, to='Epilogapp.ingredient', verbose_name='配合成分')),
            ],
        ),
    ]
