# Generated by Django 5.2 on 2025-04-23 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Epilogapp', '0008_message_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='年齢'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_concerns',
            field=models.ManyToManyField(blank=True, to='Epilogapp.concern', verbose_name='肌悩み'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/', verbose_name='プロフィール写真'),
        ),
    ]
