# Generated by Django 5.2 on 2025-04-23 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Epilogapp', '0009_customuser_age_customuser_profile_concerns_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='profile_concerns',
            new_name='concerns',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='年齢'),
        ),
    ]
