# Generated by Django 5.2 on 2025-04-30 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Epilogapp', '0015_skintype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='メールアドレス'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('クレンジング', 'クレンジング'), ('洗顔', '洗顔'), ('化粧水', '化粧水'), ('乳液', '乳液'), ('美容液', '美容液'), ('クリーム', 'クリーム')], max_length=100, verbose_name='カテゴリ'),
        ),
    ]
