# Generated by Django 5.2 on 2025-04-30 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Epilogapp', '0016_alter_customuser_email_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'このユーザー名は既に使用されています。'}, help_text='30文字以下で入力してください。英数字と @/./+/-/_ が使えます。', max_length=30, unique=True, verbose_name='ユーザー名'),
        ),
    ]
