# Generated by Django 5.2 on 2025-05-03 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Epilogapp', '0018_chatsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='Epilogapp.chatsession'),
        ),
    ]
