# Generated by Django 5.2 on 2025-05-03 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Epilogapp', '0019_message_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='available_time',
            field=models.CharField(blank=True, max_length=64, verbose_name='対応可能時間'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='certification',
            field=models.CharField(blank=True, max_length=255, verbose_name='資格'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='expertise',
            field=models.CharField(blank=True, help_text='カンマ区切りで保存', max_length=255, verbose_name='専門分野'),
        ),
    ]
