# Generated by Django 5.2 on 2025-05-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Epilogapp', '0020_customuser_available_time_customuser_certification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='skin_types',
            field=models.ManyToManyField(blank=True, to='Epilogapp.skintype', verbose_name='対応する肌質'),
        ),
    ]
