# Generated by Django 5.2 on 2025-05-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Epilogapp', '0021_product_skin_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='成分の特徴'),
        ),
    ]
